---
Meta:
  Author: "Alea"
  Description: "The personal webpage of Alea."
  Icon: "https://raw.githubusercontent.com/necrux/alea/main/assets/images/globe-icon.png"
  Twitter: ""
  Tags:
    - "Alea"
    - "Advanced Link Encapsulation Algorithm"
    - "Link Encapsulation"
Google:
  Analytics: False
  ID: 
Page:
  Color:
    Background: 'darksalmon'
    Font: 'teal'
    Clicked-Link: 'purple'
  Font: 'Sans-serif'
  Borders: False
Header:
  Title: "Welcome to Alea!"
Image:
  Path: "https://raw.githubusercontent.com/necrux/alea/main/assets/images/globe.png"
  AltText: "Globe"
Body:
  GitHub: "https://github.com/necrux/alea"
  LinkedIn: "https://www.linkedin.com/in/wes-henderson"
  MySpace: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  Resume: "https://alea.necrux.com/resume"
Footer:
  Title: "Alea: Advanced Link Encapsulation Algorithm"
  Copyright: True
