---
Meta:
  Author: "Alea"
  Description: "The resume of Alea."
  Icon: "https://raw.githubusercontent.com/necrux/alea/main/assets/images/globe-icon.png"
  Thumbnail: "https://raw.githubusercontent.com/necrux/alea/main/assets/images/globe-icon.png"
  Twitter: ""
  Tags:
    - "Alea"
    - "Resume Generator"
    - "Resume"
Google:
  Analytics: False
  ID: ""
Contact:
  Title: "Advanced Link Encapsulation Algorithm"
  Phone: "(555) 555-5555"
  Email: "wes@necrux.com"
Summary: "Alea - I do resumes now."
Skills: 
  1: "Link tree style web pages for free."
  2: "Pretty cool resumes."
Experience:
  1:
    Company: "weshenderson.info"
    Title: "Text Generator (Non-AI Division)"
    Dates: "May 2023-Present"
    Summary:
      - "Made a site for Wes."
      - "Made a resume for Wes."
Certifications:
  1:
    Title: "None"
    Year: "2023"
    License: "N/A"
Education:
  1:
    School: "Not Harvard"
    Location: "Cambridge, Massachusetts"
    Degree: "String Manipulation"
    GPA: "4.0"
    Achievements:
      - "Nothing special."
